version: '3.9'

services:
  # MongoDB Service
  mongo_db:
    container_name: db_container
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db


  # Node.js API Service
  api:
    container_name: papergenie-api
    restart: unless-stopped
    image: gopikrishna6003/paper-genie-api:latest
    environment:
      MONGODB_URI: mongodb://db_container:27017
      MONGODB_NAME: papergenie
    ports:
      - 4000:4000
    depends_on:
      - mongo_db

  # React Client Service
  client:
    container_name: papergenie-client
    restart: unless-stopped
    image: gopikrishna6003/paper-genie-client:latest
    ports:
      - 3000:3000
    depends_on:
      - api


volumes:
  mongo_db: {}
    

